logger:
  file:
    path: /var/log/open5gs/ausf.log

global:

ausf:
  sbi:
    server:
      - address: ausf.5g-mag.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.5g-mag.org:80
