gnb_id: 1

cu_cp:
  amf:
    addr: amf-with-mbs.5g-mag.org
    port: 38412
    bind_addr: gNB_IP
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
                sd: 1

cell_cfg:
  dl_arfcn: 368500
  band: 3
  channel_bandwidth_MHz: 20
  common_scs: 15
  plmn: "00101"
  tac: 1
  pci: 1
  slicing:
    - sst: 1
      sd: 1

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://gNB_IP:2000,rx_port=tcp://UE_IP:2001,base_srate=23.04e6
  srate: 23.04
  tx_gain: 75
  rx_gain: 75

expert_execution:
  threads:
    non_rt:
      nof_non_rt_threads: 2

log:
  filename: /tmp/gnb_with_mbs.log
  all_level: info
  hex_max_size: 0

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_with_mbs_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_with_mbs_ngap.pcap
