logger:
  file:
    path: /var/log/open5gs/mb-upf.log

global:

upf:
  pfcp:
    server:
      - address: mb-upf.5g-mag.org
    client:
  gtpu:
    server:
      - address: mb-upf.5g-mag.org
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
