logger:
  file:
    path: /var/log/open5gs/smf_mb-smf.log

global:

smf:
  sbi:
    server:
      - address: smf-mb-smf.5g-mag.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.5g-mag.org:80
  pfcp:
    server:
      - address: smf-mb-smf.5g-mag.org
    client:
      upf:
        - address: upf-mb-upf.5g-mag.org
  gtpu:
    server:
      - address: smf-mb-smf.5g-mag.org
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
  info:
    - s_nssai:
        - sst: 1
          sd: 1
          dnn:
            - internet
      tai:
        - plmn_id:
            mcc: 001
            mnc: 01
          tac: 1
