services:
  db:
    container_name: db
    image: "mongo:${MONGODB_VERSION}"
    command: "mongod --bind_ip 0.0.0.0 --port 27017"
    networks:
      5g-mag:
        aliases:
          - db.5g-mag.org
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

  nrf:
    container_name: nrf
    image: "ghcr.io/5g-mag/nrf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/nrf.yaml"
    networks:
      5g-mag:
        aliases:
          - nrf.5g-mag.org
    configs:
      - source: nrf_config
        target: /etc/open5gs/custom/nrf.yaml

  ausf:
    container_name: ausf
    image: "ghcr.io/5g-mag/ausf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/ausf.yaml"
    networks:
      5g-mag:
        aliases:
          - ausf.5g-mag.org
    configs:
      - source: ausf_config
        target: /etc/open5gs/custom/ausf.yaml
    depends_on:
      - nrf

  udm:
    container_name: udm
    image: "ghcr.io/5g-mag/udm:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/udm.yaml"
    networks:
      5g-mag:
        aliases:
          - udm.5g-mag.org
    configs:
      - source: udm_config
        target: /etc/open5gs/custom/udm.yaml
    depends_on:
      - nrf

  udr:
    container_name: udr
    image: "ghcr.io/5g-mag/udr:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/udr.yaml"
    restart: unless-stopped
    networks:
      5g-mag:
        aliases:
          - udr.5g-mag.org
    configs:
      - source: udr_config
        target: /etc/open5gs/custom/udr.yaml
    depends_on:
      - db
      - nrf

  nssf:
    container_name: nssf
    image: "ghcr.io/5g-mag/nssf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/nssf.yaml"
    networks:
      5g-mag:
        aliases:
          - nssf.5g-mag.org
    configs:
      - source: nssf_config
        target: /etc/open5gs/custom/nssf.yaml
    depends_on:
      - nrf

  bsf:
    container_name: bsf
    image: "ghcr.io/5g-mag/bsf:${OPEN5GS_VERSION}"
    command: "-c /open5gs/config/bsf.yaml"
    networks:
      5g-mag:
        aliases:
          - bsf.5g-mag.org
    configs:
      - source: bsf_config
        target: /open5gs/config/bsf.yaml
    depends_on:
      - nrf

  pcf:
    container_name: pcf
    image: "ghcr.io/5g-mag/pcf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/pcf.yaml"
    restart: unless-stopped
    networks:
      5g-mag:
        aliases:
          - pcf.5g-mag.org
    configs:
      - source: pcf_config
        target: /etc/open5gs/custom/pcf.yaml
    depends_on:
      - db
      - nrf

  webui:
    container_name: webui
    image: "ghcr.io/5g-mag/webui:${OPEN5GS_VERSION}"
    environment:
      - DB_URI=mongodb://db.5g-mag.org/open5gs
      - PORT=9999
      - HOSTNAME=0.0.0.0
      - NODE_ENV=dev
    command: "run dev"
    networks:
      5g-mag:
        aliases:
          - webui.5g-mag.org
    depends_on:
      - db
    ports:
      - "0.0.0.0:9999:9999/tcp"

  mb-amf:
    container_name: mb-amf
    image: "ghcr.io/5g-mag/mb-amf:${FIVEG_MAG_MBS_VERSION}"
    command: "-c /etc/open5gs/custom/mb-amf.yaml"
    networks:
      5g-mag:
        aliases:
          - mb-amf.5g-mag.org
    configs:
      - source: mb_amf_config
        target: /etc/open5gs/custom/mb-amf.yaml
    depends_on:
      - nrf

  mb-smf:
    container_name: mb-smf
    image: "ghcr.io/5g-mag/mb-smf:${FIVEG_MAG_MBS_VERSION}"
    command: "-c /etc/open5gs/custom/mb-smf.yaml"
    networks:
      5g-mag:
        aliases:
          - mb-smf.5g-mag.org
    configs:
      - source: mb_smf_config
        target: /etc/open5gs/custom/mb-smf.yaml
    depends_on:
      - nrf
      - mb-upf

  mb-upf:
    container_name: mb-upf
    image: "ghcr.io/5g-mag/mb-upf:${FIVEG_MAG_MBS_VERSION}"
    command: "-c /etc/open5gs/custom/mb-upf.yaml"
    networks:
      5g-mag:
        aliases:
          - mb-upf.5g-mag.org
    configs:
      - source: mb_upf_config
        target: /etc/open5gs/custom/mb-upf.yaml
    privileged: true
    cap_add:
      - NET_ADMIN

  af:
    container_name: af
    image: "ghcr.io/5g-mag/af:${FIVEG_MAG_MBS_VERSION}"
    networks:
      5g-mag:
        aliases:
          - af.5g-mag.org
    volumes:
      - ../../test:/test:ro

  mb-gnb:
    container_name: mb-gnb
    image: "ghcr.io/5g-mag/mb-gnb:${FIVEG_MAG_MBS_VERSION}"
    environment:
      - GNB_FQDN=mb-gnb.5g-mag.org
      - UE_FQDN=mb-ue.5g-mag.org
    command: "-c /etc/rt-srsRAN_Project/custom/mb-gnb.yaml"
    networks:
      5g-mag:
        aliases:
          - mb-gnb.5g-mag.org
    configs:
      - source: mb_gnb_config
        target: /etc/rt-srsRAN_Project/custom/mb-gnb.yaml
    privileged: true
    cap_add:
      - NET_ADMIN
    depends_on:
      - mb-amf

  mb-ue:
    container_name: mb-ue
    image: "ghcr.io/5g-mag/mb-ue:${FIVEG_MAG_MBS_VERSION}"
    environment:
      - UE_FQDN=mb-ue.5g-mag.org
      - GNB_FQDN=mb-gnb.5g-mag.org
    command: "/etc/srsRAN_4G/custom/mb-ue.conf"
    networks:
      5g-mag:
        aliases:
          - mb-ue.5g-mag.org
    configs:
      - source: mb_ue_config
        target: /etc/srsRAN_4G/custom/mb-ue.conf
    privileged: true
    cap_add:
      - NET_ADMIN
    depends_on:
      - mb-gnb

networks:
  5g-mag:
    name: 5g-mag
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-5g-mag
    ipam:
      config:
        - subnet: 10.33.33.0/24

volumes:
  db_data:
    name: open5gs_db_data
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}
  db_config:
    name: open5gs_db_config
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}

configs:
  nrf_config:
    file: ../../configs/internal/nrf.yaml
  ausf_config:
    file: ../../configs/internal/ausf.yaml
  udm_config:
    file: ../../configs/internal/udm.yaml
  udr_config:
    file: ../../configs/internal/udr.yaml
  nssf_config:
    file: ../../configs/internal/nssf.yaml
  bsf_config:
    file: ../../configs/internal/bsf.yaml
  pcf_config:
    file: ../../configs/internal/pcf.yaml
  mb_amf_config:
    file: ../../configs/internal/mb-amf.yaml
  mb_smf_config:
    file: ../../configs/internal/mb-smf.yaml
  mb_upf_config:
    file: ../../configs/internal/mb-upf.yaml
  mb_gnb_config:
    file: ../../configs/internal/mb-gnb.yaml
  mb_ue_config:
    file: ../../configs/internal/mb-ue.conf
